version: '3'

services: 

  app:
    build: 
      context: ./node
    image: nodeapp
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: npm run dev
    networks: 
      - node-network
    volumes: 
      - ./node:/home/src/
      - /home/src/node_modules
    tty: true
    depends_on: 
       - db

  nginx:
    image: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on:
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks: 
  node-network:
    name: node-network
    driver: bridge      
